nginx:
  image: "registry.cn-hangzhou.aliyuncs.com/marmot/nginx-base"
  ports:
    - "80:80"
  external_links:
    - "huizhonglianhe-oa-nginx"
    - "huizhonglianhe-portal-nginx"
  volumes:
    - ./conf.d/:/etc/nginx/conf.d/
  container_name: reverse
