#!/bin/bash

function installPortal {
  if [ ! -d "./code" ]; then
    cd $smartPath && git clone https://code.aliyun.com/huijiabei/code.git
  fi
  cd code && git checkout dev && docker-compose up -d && cp pre-commit .git/hooks && ./smart composer && cd $smartPath
}

function startPortal {
  cd code && git checkout dev && docker-compose up -d && cd $smartPath
}

function stopPortal {
  cd code && git checkout dev && docker-compose stop && cd $smartPath
}

function clearPortal {
  cd code && git checkout dev && docker-compose stop && docker-compose rm -f && docker-compose pull && cd $smartPath
}

function updatePortal {
  cd code && git checkout dev && git pull origin dev && cd $smartPath
}
