#!/bin/bash

function installMemberApi {
  if [ ! -d "./huizhonglianhe-backend-member" ]; then
  cd $smartPath && git clone https://code.aliyun.com/huizhonglianhe/huizhonglianhe-backend-member.git
  fi
  cd huizhonglianhe-backend-member && git checkout dev && docker-compose up -d && ./smart composer && chmod +x vendor/bin/* && cd $smartPath
}

function startMemberApi {
  cd huizhonglianhe-backend-member && git checkout dev && docker-compose up -d && cd $smartPath
}

function stopMemberApi {
  cd huizhonglianhe-backend-member && git checkout dev && docker-compose stop && cd $smartPath
}

function clearMemberApi {
  cd huizhonglianhe-backend-member && git checkout dev && docker-compose stop && docker-compose rm -f && docker-compose pull && cd $smartPath
}

function updateMemberApi {
  cd huizhonglianhe-backend-member && git checkout dev && git pull origin dev && cd $smartPath
}