#!/bin/bash

function installOa {
  if [ ! -d "./huizhonglianhe-frontend-oa" ]; then
    cd $smartPath && git clone https://code.aliyun.com/huizhonglianhe/huizhonglianhe-frontend-oa.git
  fi
  cd huizhonglianhe-frontend-oa && git checkout dev && docker-compose up -d && cp pre-commit .git/hooks && ./smart composer && chmod +x vendor/bin/* && cd $smartPath
}

function startOa {
  cd huizhonglianhe-frontend-oa && git checkout dev && docker-compose up -d && cd $smartPath
}

function stopOa {
  cd huizhonglianhe-frontend-oa && git checkout dev && docker-compose stop && cd $smartPath
}

function clearOa {
  cd huizhonglianhe-frontend-oa && git checkout dev && docker-compose stop && docker-compose rm -f && docker-compose pull && cd $smartPath
}

function updateOa {
  cd huizhonglianhe-frontend-oa && git checkout dev && git pull origin dev && cd $smartPath
}
