#!/bin/bash

function installPortal {
  if [ ! -d "./huizhonglianhe-frontend-portal" ]; then
    cd $smartPath && git clone https://code.aliyun.com/huizhonglianhe/huizhonglianhe-frontend-portal.git
  fi
  cd huizhonglianhe-frontend-portal && git checkout dev && docker-compose up -d && cp pre-commit .git/hooks && ./smart composer && chmod +x vendor/bin/* && cd $smartPath
}

function startPortal {
  cd huizhonglianhe-frontend-portal && git checkout dev && docker-compose up -d && cd $smartPath
}

function stopPortal {
  cd huizhonglianhe-frontend-portal && git checkout dev && docker-compose stop && cd $smartPath
}

function clearPortal {
  cd huizhonglianhe-frontend-portal && git checkout dev && docker-compose stop && docker-compose rm -f && docker-compose pull && cd $smartPath
}

function updatePortal {
  cd huizhonglianhe-frontend-portal && git checkout dev && git pull origin dev && cd $smartPath
}
