#!/bin/bash

smartPath=`pwd`
#加载公共smart函数库
. ./smart-scripts/shell/smartfunc/smartfunc

#加载base函数库
. ./smart-scripts/shell/smartfunc/basefunc

#加载项目函数库
. ./smart-scripts/shell/smartfunc/oafunc
. ./smart-scripts/shell/smartfunc/protalfunc
. ./smart-scripts/shell/smartfunc/memberapifunc
. ./smart-scripts/shell/smartfunc/reversefunc

case $1 in
'install')
  installBasement
  installMemberApi
  installOa
  installPortal
  installReverse
  addHosts
  ;;
'start')
  startBasement
  startMemberApi
  startOa
  startPortal
  startReverse
  ;;
'stop')
  stopBasement
  stopMemberApi
  stopOa
  stopPortal
  stopReverse
  ;;
'clear')
  clearBasement
  clearPortal
  clearMemberApi
  clearOa
  ;;
'upgrade')
  clearMemberApi
  clearOa
  clearPortal
  clearReverse
  startMemberApi
  startOa
  startPortal
  startReverse
  ;;
'test')
  ;;
*)
  menu
esac